use crate::backend_type::BackendType;
use crate::column::ColumnType;
use bincode::{Decode, Encode, config};

use darling::{FromField, FromMeta};
use quote::ToTokens;
use syn::Field;

fn parse_column_type(col: String) -> Option<ColumnType> {
    Some(col.as_str().into())
}

#[derive(Debug, Default, Encode, Decode)]
pub struct FieldDefinition {
    col_name: String,
    col_type: ColumnType,
    auto: bool, // autoincrement field
    unique: bool,
    primary: bool,
    default_value: Option<String>,
    length: Option<usize>,
    foreign_key: Option<FkOptions>,
}

#[derive(FromField, Default)]
#[darling(attributes(modeller))]
pub struct FieldOptions {
    #[darling(rename = "name")]
    col_name: Option<String>,

    #[darling(rename = "type", map = "parse_column_type")]
    col_type: Option<ColumnType>,
    auto: Option<bool>, // autoincrement field
    unique: Option<bool>,
    primary: Option<bool>,

    #[darling(rename = "default")]
    default_value: Option<String>,
    length: Option<usize>,

    foreign_key: Option<FkOptions>,
    not_id: Option<bool>,
}

impl FieldDefinition {
    pub fn to_sql(&self, bt: &BackendType) -> String {
        let col = &self.col_name;
        let col_type = &self.col_type.to_sql(&self.length, bt);
        let unique = self.unique_sql();
        let primary = self.primary_sql();
        let serial = self.auto_sql(bt);

        let default_value = &self
            .default_value
            .as_ref()
            .map(|v| format!("DEFAULT \"{}\"", v.trim()))
            .unwrap_or_default();

        format!("{col} {col_type} {primary} {serial} {unique} {default_value}")
    }

    fn unique_sql(&self) -> &str {
        if self.unique { "UNIQUE" } else { "" }
    }

    fn primary_sql(&self) -> &str {
        if self.primary { "PRIMARY KEY" } else { "" }
    }

    fn auto_sql(&self, bt: &BackendType) -> &str {
        use BackendType::*;

        if self.auto {
            match bt {
                MySql => "AUTO_INCREMENT",
                Postgres => "GENERATED ALWAYS AS IDENTITY",
                Sqlite => "AUTOINCREMENT",
            }
        } else {
            ""
        }
    }

    pub fn accept_opts(&mut self, opts: FieldOptions) {
        let FieldOptions {
            col_name,
            col_type,
            auto,
            unique,
            primary,
            default_value,
            length,
            foreign_key,
            not_id,
        } = opts;
        if let Some(name) = col_name {
            self.col_name = name
        }

        if let Some(ct) = col_type {
            self.col_type = ct
        }

        self.auto = auto.unwrap_or_default();
        self.unique = unique.unwrap_or_default();
        self.primary = primary.unwrap_or_default();
        self.default_value = default_value;
        self.length = length;
        self.foreign_key = foreign_key;

        let not_id = not_id.unwrap_or_default();

        // unless user disables this (by setting not_id to false)
        // `id` fields will be autogenerated primary keys
        if self.col_name() == "id" && !not_id {
            self.auto = true;
            self.primary = true;

            // make field an integer type
            self.col_type = ColumnType::Nullable(Box::new(ColumnType::Int32));
        }
    }

    pub fn col_name(&self) -> &str {
        &self.col_name
    }

    pub fn foreign_key(&self) -> &Option<FkOptions> {
        &self.foreign_key
    }
}

impl From<&Field> for FieldDefinition {
    fn from(value: &Field) -> Self {
        let Field { ident, ty, .. } = value;
        let col_name = ident
            .as_ref()
            .map(|v| v.to_token_stream().to_string())
            .unwrap_or("".to_string());

        let col_type = ty.into();

        FieldDefinition {
            col_name,
            col_type,
            ..Default::default()
        }
    }
}

impl PartialEq for FieldDefinition {
    fn eq(&self, other: &Self) -> bool {
        let config = config::standard();
        let s = bincode::encode_to_vec(self, config);
        let o = bincode::encode_to_vec(other, config);

        if let (Ok(s), Ok(o)) = (s, o) {
            s == o
        } else {
            false
        }
    }
}

#[derive(Debug, Default, Encode, Decode, FromMeta)]
pub struct FkOptions {
    rf: String,
    on_delete: FkOnDelete,
}

impl FkOptions {
    pub fn references(&self) -> &str {
        &self.rf
    }

    pub fn on_delete(&self) -> &FkOnDelete {
        &self.on_delete
    }
}

impl FkOptions {
    pub fn to_sql(&self, col_name: &str) -> String {
        format!(
            "FOREIGN KEY ({}) REFERENCES {} ON DELETE {}",
            col_name,
            self.rf,
            self.on_delete.to_sql()
        )
    }
}

#[derive(Debug, Default, Encode, Decode, PartialEq, FromMeta)]
pub enum FkOnDelete {
    Cascade,
    Nullify,
    Default,
    Restrict,

    #[default]
    NoAction,
}

impl FkOnDelete {
    pub fn to_sql(&self) -> String {
        use FkOnDelete::*;

        let sql = match self {
            Cascade => "CASCADE",
            Nullify => "SET NULL",
            Default => "SET DEFAULT",
            Restrict => "RESTRICT",
            NoAction => "NO ACTION",
        };

        sql.to_string()
    }
}
